// <auto-generated />
using System;
using DisneyApi.AppCode.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DisneyApi.Migrations
{
    [DbContext(typeof(GlobalDbContext))]
    [Migration("20211127184801_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DisneyApi.AppCode.Domain.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("CharacterId");

                    b.HasIndex("Name");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 6,
                            Age = 14,
                            Name = "Pluto",
                            Weight = 20.00m
                        },
                        new
                        {
                            CharacterId = 7,
                            Age = 24,
                            Name = "Donald",
                            Weight = 3.00m
                        },
                        new
                        {
                            CharacterId = 10,
                            Age = 24,
                            Name = "Mickey",
                            Weight = 30.00m
                        },
                        new
                        {
                            CharacterId = 12,
                            Age = 20,
                            Name = "Dumbo",
                            Weight = 30.00m
                        },
                        new
                        {
                            CharacterId = 15,
                            Age = 98,
                            Name = "Tio rico",
                            Weight = 30.00m
                        },
                        new
                        {
                            CharacterId = 16,
                            Age = 24,
                            Name = "Bruno",
                            Weight = 30.00m
                        });
                });

            modelBuilder.Entity("DisneyApi.AppCode.Domain.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Western"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Cartoon"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Terror"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "Adventures"
                        },
                        new
                        {
                            GenreId = 11,
                            Name = "Biography"
                        },
                        new
                        {
                            GenreId = 12,
                            Name = "Future"
                        });
                });

            modelBuilder.Entity("DisneyApi.AppCode.Domain.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.HasIndex("Title");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 5,
                            CreateDate = new DateTime(1940, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Rating = "4",
                            Title = "Pluto"
                        },
                        new
                        {
                            MovieId = 6,
                            CreateDate = new DateTime(1994, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Rating = "4",
                            Title = "El rey león"
                        },
                        new
                        {
                            MovieId = 12,
                            CreateDate = new DateTime(1950, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = "4",
                            Title = "Pinocho"
                        });
                });

            modelBuilder.Entity("DisneyApi.AppCode.Domain.Playing", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("Playings");

                    b.HasData(
                        new
                        {
                            CharacterId = 7,
                            MovieId = 5
                        },
                        new
                        {
                            CharacterId = 10,
                            MovieId = 5
                        },
                        new
                        {
                            CharacterId = 16,
                            MovieId = 5
                        },
                        new
                        {
                            CharacterId = 16,
                            MovieId = 6
                        });
                });

            modelBuilder.Entity("DisneyApi.AppCode.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DisneyApi.AppCode.Domain.Movie", b =>
                {
                    b.HasOne("DisneyApi.AppCode.Domain.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DisneyApi.AppCode.Domain.Playing", b =>
                {
                    b.HasOne("DisneyApi.AppCode.Domain.Character", "Character")
                        .WithMany("Playings")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisneyApi.AppCode.Domain.Movie", "Movie")
                        .WithMany("Cast")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
